### ISSUE TITLE
Doc Request: Feature Comparison Chart with mosquitto

### ISSUE THREAD

**Issue by ssnover** [bschwind/mqtt-broker#28]
I think mosquitto is one of the more well-known open source MQTT broker implementations and I think it'd make sense to have a section of the README devoted to a comparison of features. Obviously mosquitto is a very mature project at this point, but I think it'd be helpful as a starting point for discussing new features.

My team is currently using mosquitto in production and have had a couple issues with features breaking in patch builds. While we're not opposed to making bug fixes in mosquitto, we primarily develop in Rust, not C, and it'd be much easier for us to contribute changes or features to a Rust-based broker.

Some features I know we'd be looking for: bridging between brokers, websockets connections, and persistent storage. This issue isn't asking for those things, just for a list of features that are different so I know where I (and others) could start contributing.

**Comment by bschwind** [comment]
Hi, this is a great idea as this project maybe has different goals. I can write up those goals, as well as a feature comparison between mosquitto and some other brokers.

The summary is, I wanted a simple MQTT v5 broker written in Rust that was to be used for IoT products, especially where the end consumer of these IoT products could easily run their own broker. My goal was to go through the entire v5 spec and implement it with Rust + tokio. This was both to get used to writing async/await code in Rust, and also to hopefully have a functioning and fast broker.

If you haven't already, I would also check out rumqtt: https://github.com/bytebeamio/rumqtt

It appears to have more of a community around it, and much more active development. I'm not at all opposed to pull requests but I'm pretty sure I have less time and resources than rumqtt when it comes to reviewing and testing so please keep that in mind.

In any case, thanks for bringing this up, and I'll try to write a short comparison to other brokers. That might also help me turn it into a TODO list which is also needed.

**Comment by bschwind** [comment]
Hi @ssnover - I created a milestone for viewing the progress of V5 spec compliance, you can view it here:

https://github.com/bschwind/mqtt-broker/milestone/1

The README has also been updated with project goals, and some links to other brokers.

The spec milestone is probably still missing some issues, feel free to add them if you notice any.

**Comment by ssnover** [comment]
Thanks!
