### ISSUE TITLE
Separate broker and main

### ISSUE THREAD

**Issue by flxo** [bschwind/mqtt-broker#44]
The `mqtt-v5-broker` crate is a binary. The `main` opens the listeners and forwards clients to the broker state upon connects.
When playing with the broker the code in `main` is kind of integration specific and one would like to implement specific things prior to the broker start and where to listen etc....

Splitting the crate into a lib and a example main would allow to implement a custom main with custom logging, listeners etc... 

Steps are:

* create `src/lib.rs`
* move the `mod` from `main.rs` to `lib.rs`
* decide what need to be pub exported in `lib.rs` e.g `pub use mqtt-v5-broker::broker::Broker;`
* move `client_handler`, `upgrade_stream` and `websocket_client_handler` to `client.rs` and slightly refactor?

**Comment by bschwind** [comment]
You're absolutely right about this, it should be much easier to run your own broker with customized logging and hooks into the various events that occur with a broker.

I haven't thought through all the details yet, but what you've mentioned so far sounds reasonable.

**Comment by flxo** [comment]
I will post a draft. :-)
